// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etesmmtpylxoaeoepgsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZXNtbXRweWx4b2Flb2VwZ3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzA5ODUsImV4cCI6MjA2NTk0Njk4NX0.Jykkt0tOItNi7yHlWCoC5kxWmfLYXCvxab3NpnK8T2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);